# syntax=docker/dockerfile:1

FROM ghcr.io/york-fs/monorepo:master

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y software-properties-common \
 && apt-add-repository --yes ppa:kicad/kicad-9.0-releases \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    jq \
    kicad \
    kicad-packages3d \
    kicad-symbols \
 && rm -rf /var/lib/apt/lists/*
