name: Code Style
on: [workflow_call]

jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    container: ghcr.io/york-fs/monorepo:master
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format
        shell: bash
        run: |
          git config --global --add safe.directory $(pwd)
          find . \( -name '*.cc' -or -name '*.hh' \) |
          xargs clang-format -i
          git diff | tee format-diff
          if [ -s format-diff ]; then exit 1; fi
